# Introduction à l'algèbre lineaire

Nous réviserons les concepts de base de l'algèbre linéaire nécessaires pour porsuivre ce cours. L'objectif de ce Jupyter notebook est de se familiariser avec l'algèbre lineaire et la librarie NumPy en Python. Il est important de suivre les étapes de ce cours et de pratiquer. 

1) Vecteurs et matrices

2) Opérations entre vecteurs et matrices

3) Multiplication de matrices

4) Indexation des matrices

Pour suivre ce notebook, il faut avoir NumPy installé dans votre environment Python. Vous pouvez simplement l'installé avec le commande:

**pip install numpy**

Si vous utilisez ce notebook avec Google Colab, NumPy est déjà installé et vous devriez être en mesure de suivre ce guide.

# NumPy et la vectorisation

NumPy est une bibliothèque de calcul scientifique **extrêmement optimisée** pour Python.
Documentation NumPy: https://numpy.org

La compréhension de l'algèbre linéaire est essentielle pour développer des modèles d'apprentissage automatique à partir de zéro. En utilisant NumPy nous pouvons rendre nos calculs plus efficaces et plus simples. NumPy simplifie votre code et augmente les performances en même temps!


Au fil du temps, vous apprendrez à apprécier NumPy de plus en plus.

## 1) Vecteurs

* Un vecteur est un array de nombres disposés dans l'ordre. Chaque élément peut être identifié par son indice.


\begin{equation}
\mathbf{a} = \begin{bmatrix}a_1, a_2, ..., a_n \end{bmatrix}
\end{equation}

Nous pouvons considérer les vecteurs comme un **point dans un espace multidimensionnel**. Chaque élément représente la coordonnée dans un axe différent.



In [1]:
import numpy as np 

print(np.ones(4)) # Vector de 4 elements de 1
print(np.zeros(4)) # Vector de 4 elements de 0
a = np.array([1.,4.,4, 5.,6.,7])
print(a)
# pour avoir le nombre de lignes et de colonnes de la matrice a
# on utilise shape
print(a.shape) #1 ligne, aucune colonne

[1. 1. 1. 1.]
[0. 0. 0. 0.]
[1. 4. 4. 5. 6. 7.]
(6,)


### 1.1) Vector Operations

\begin{equation}
\mathbf{a} = \begin{bmatrix}
a_1, \;  a_2, \; ... ,\; a_n
\end{bmatrix}
\end{equation}

\begin{equation}
\mathbf{b} = \begin{bmatrix}b_1, \; b_2 \;  ... \;  b_n \end{bmatrix}
\end{equation}

#### 1) Somme:
\begin{equation}
n + \mathbf{a} = \begin{bmatrix}a_1 + n, \:  a_2 + n, \:  ..., \:  a_n + n \end{bmatrix}
\end{equation}


#### 2) Multiplication par un scalaire $ex: 3$:

\begin{equation}
n * \mathbf{a} = \begin{bmatrix}3a_1 , \:  3a_2 , \:  ..., \:  3a_n \end{bmatrix}
\end{equation}

## Les opérations
Les opérations de base de numpy sont élément par élément

In [2]:
a = np.ones(4)
print(a)
b = a * 8
print(b)
c = np.log2(b)
print(c)

[1. 1. 1. 1.]
[8. 8. 8. 8.]
[3. 3. 3. 3.]


#### 3) Produit scalaire entre vecteurs (dot product): 

\begin{equation}
\mathbf{a} \cdot \mathbf{b} = (a_1 \times b_1) \: + \:  (a_2 \times b_2) \: + \: ... \: + \: (a_n \times b_n)
\end{equation}


#### 4) Element-wise (Hadamard)

\begin{equation}
\mathbf{a} * \mathbf{b} = \begin{bmatrix}a_1 \times b_1, \; a_2 \times b_2, \; ..., \; a_n \times b_n \end{bmatrix}
\end{equation}



In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8])
# dot product
print(a.dot(b))

# Hadamard
print(a * b)

32
[ 4 10 18]


In [4]:
c = np.array([7, 8])

# Erreur:
a.dot(c)

# Erreur:
a * c

ValueError: shapes (3,) and (2,) not aligned: 3 (dim 0) != 2 (dim 0)

## 2) Matrice

Une matrice est un tableau de nombres en 2D désigné par une variable majuscule $\mathbf{A}$. Chaque élément $a_{ij}$ est identifié par deux indices, l'indice de ligne $"i"$ et l'indice de colonne $"j"$. 

\begin{equation}
\mathbf{A} = \begin{bmatrix}
a_{11} & a_{12} \\ 
a_{21} &  a_{22}\\ 
\end{bmatrix}
\end{equation}

\begin{equation}
\mathbf{B} = \begin{bmatrix}
b_{11} & b_{12} \\ 
b_{21} &  b_{22}\\ 
\end{bmatrix}
\end{equation}


In [ ]:
A = np.array([[1,1],[2,2]])
B = np.array([[-1,1],[1,1]])

## Operations Matricielles:

\begin{equation}
	A -B =
	\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} 	
	\end{bmatrix} -
	\begin{bmatrix} b_{11} & b_{12} \\
	  b_{21} & b_{22}
	\end{bmatrix}
	=
	\begin{bmatrix}
	  a_{11}-b_{11} & a_{12}-b_{12} \\
	  a_{21}-b_{21} & a_{22}-b_{22} 	
	\end{bmatrix}
\end{equation}


\begin{equation}
	A + B =
	\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} 	
	\end{bmatrix} +
	\begin{bmatrix} b_{11} & b_{12} \\
	  b_{21} & b_{22}
	\end{bmatrix}
	=
	\begin{bmatrix}
	  a_{11}+b_{11} & a_{12}+b_{12} \\
	  a_{21}+b_{21} & a_{22}+b_{22} 	
	\end{bmatrix}
\end{equation}


#### Multiplication par un scalaire ($ex: 3$):

\begin{equation}
	3 \times A = 3 \times \begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} 	
	\end{bmatrix}
	=
	\begin{bmatrix}
	  3a_{11} & 3a_{12} \\
	  3a_{21} & 3a_{22} 	
	\end{bmatrix}
\end{equation}

In [ ]:
print(A - B)
print (A + B)
print(3 * A)

### 2.1) Transpose

One important operation on matrices is the **transpose**. The transpose of a matrix is the mirror image of the matrix across a diagonal line (main diagonal). We denote the transpose of a matrix $\mathbf{A}$ as $\mathbf{A}^T$ such that:

\begin{equation}
(\mathbf{A}^{T})_{i, j} = \mathbf{A}_{j, i}
\end{equation}

Exemple:

\begin{equation}
\mathbf{A} = \begin{bmatrix}
a_{1,1} & a_{1,2}  \\ 
a_{2,1} &  a_{2,2}\\ 
a_{3,1} & a_{3,2} 
\end{bmatrix} \Rightarrow  \mathbf{A}^{T} = \begin{bmatrix}
a_{1,1} & a_{2,1} & a_{3, 1} \\ 
a_{1,2} &  a_{2,2} & a_{3, 2}\\ 
\end{bmatrix}
\end{equation}




In [ ]:
A = np.array([[1,2],
              [3,4],
              [5,6]])
print(A)
print(f"Shape: {A.shape}")

# Transpose
print(A.T)
print(f"Shape: {A.T.shape}")
# on peut aussi utiliser np.transpose

print(np.transpose(A))

###  2.1) Produit matrices

Le produit de deux matrices ne peut se définir que si le nombre de **colonnes** de la première matrice est le même que le nombre de **lignes** de la deuxième matrice, c'est-à-dire lorsqu'elles sont de type compatible.

* Considérez le $2 \times 1$ vecteur $B=\bigl( \begin{smallmatrix} b_{11} \\
  b_{21}
\end{smallmatrix} \bigr)$  Le vecteur colonne et correspond à un cas particulier de matrice.

\begin{equation}
	\mathbf{A}_{2 \times 2} \times \mathbf{B}_{2 \times 1} = 
	\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} 	
	\end{bmatrix}_{2 \times 2}
    \times
    \begin{bmatrix}
	b_{11} \\
	b_{21}
	\end{bmatrix}_{2 \times 1}
	=
	\begin{bmatrix}
	  a_{11}b_{11} + a_{12}b_{21} \\
	  a_{21}b_{11} + a_{22}b_{21} 	
	\end{bmatrix}_{2 \times 1}
\end{equation}

In [ ]:
# Essayez changer ces valeurs de A et B
A = np.arange(4).reshape((2,2))
B = np.random.randn(2,1) 
print(A)
print(B)
print(A.shape)
print(B.shape)

Le résulat:

In [ ]:
print(A.dot(B))
# alternative
print(np.dot(A,B))
np.dot(A,B).shape

* On peut aussi considérer une matrice C de dimension $2 \times 3$ et une matrice A de dimension $3 \times 2$.

\begin{equation}
	\mathbf{A}_{3 \times 2}=\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} \\
	  a_{31} & a_{32} 	
	\end{bmatrix}_{3 \times 2}
	,
	\mathbf{C}_{2 \times 3} = 
	\begin{bmatrix}
		  c_{11} & c_{12} & c_{13} \\
		  c_{21} & c_{22} & c_{23} \\
	\end{bmatrix}_{2 \times 3}
	\end{equation}
    
\begin{align}
	\mathbf{A}_{3 \times 2} \times \mathbf{C}_{2 \times 3}=&
	\begin{bmatrix}
	  a_{11} & a_{12} \\
	  a_{21} & a_{22} \\
	  a_{31} & a_{32} 	
	\end{bmatrix}_{3 \times 2}
	\times
	\begin{bmatrix}
	  c_{11} & c_{12} & c_{13} \\
	  c_{21} & c_{22} & c_{23} 
	\end{bmatrix}_{2 \times 3} \\
	=&
	\begin{bmatrix}
	  a_{11} c_{11}+a_{12} c_{21} & a_{11} c_{12}+a_{12} c_{22} & a_{11} c_{13}+a_{12} c_{23} \\
	  a_{21} c_{11}+a_{22} c_{21} & a_{21} c_{12}+a_{22} c_{22} & a_{21} c_{13}+a_{22} c_{23} \\
	  a_{31} c_{11}+a_{32} c_{21} & a_{31} c_{12}+a_{32} c_{22} & a_{31} c_{13}+a_{32} c_{23}
	\end{bmatrix}_{3 \times 3}	
\end{align}

In [ ]:
A = np.array([[1,2],[3,4],[5, 6]])
C = np.array([[1,2,3], [1, 2, 3]])
A.dot(C)

* Remarquez que $\mathbf{C} \times \mathbf{A}$ donne un résultat entièrement different. 

In [ ]:
A = np.array([[1,2],[3,4],[5, 6]])
C = np.array([[1,2,3], [1, 2, 3]])
print(C.dot(A))

### IMPORTANT: L'opérateur multiplicateur de Python "*" correspond au produit Hadamard

In [ ]:
A = np.arange(4).reshape((2,2))
B = np.array([[0, 0], [-1, -1]]) 
A * B

## Indexing

Un tableau/vecteur/matrice/tenseur de Numpy peut être indexé de plusieurs façons. **Note: l'indexage en Numpy commence par zéro.**

Exemple:
   





In [ ]:
A = np.array([[1,2,3],
              [4,5,6]])
print(A)

In [ ]:
#A has 2 rows and 3 columns.
A.shape

In [ ]:
print(A[0,1]) # retourne "2": l'élément de la ligne 0, colonne 1
print(A[1,2]) # retourne "6": l'élément de la ligne 1, colonne 2

In [ ]:
A[2,0] # Error: Cette matrice n'a que 2 lines

En Python, on peut utiliser le symbol ":" pour indexer. Utilisé seul, le symbol veut dire soit "tous les lignes ou tous les colonnes".

In [ ]:
print(A[:, 0]) # returns [1, 4] - la colonne 0

print(A [1,:]) # returns [4,5,6] - la ligne 1

On peut également utiliser le symbol ":" pour indexer partiellement une matrice.

In [ ]:
print(A[0,1:]) # retourne [2,3]: l'élément de la ligne 0, colonne 1 à la fin

print(A[0,: 2]) # retourne [1,2]: l'élément de la ligne 0, colonne 0 jusqu'à 2 (= retourn colonne 0 et 1)

## Python list à Numpy array

Il est très facile de convertir une list à un NumPy array:

**Note:** Il faut toujours convertir list à un NumPy array pour pouvoir utiliser les fonctionalités de NumPy.

In [ ]:
l = [[1,2,3], [4,5,6]]
print(f"List: {l}")
na = np.array(l)
print(f"NumPy array: {na}")

## Représentation graphique

Une façon de voir les matrices est de les considérer comme une collection de vecteurs (points dans l'espace). Nous pouvons considérer chaque ligne de la matrice comme. Cette notion sera cruciale durant ce cours.

Nous pouvons afficher ces point avec l'aide de **matplotlib**

In [ ]:
import matplotlib.pyplot as plt
from sklearn import datasets
M = np.array([[1, 2],
              [1.5, 3],
              [3, 4.5],
              [4,5],
              [1, 1.5],
              [2, 3],
              [2, 3.5]])

plt.scatter(M[:,0], M[:,1],  color='black')
plt.xlabel('variable 1')
plt.ylabel('variable 2')
plt.show()

## Exercice 

1. calculer la distance euclidienne entre le vecteur $\mathbf{a}$ et chaque ligne (row) appartenant à la matrice $\mathbf{B}$ (chaque ligne peut être considéré comme un différent vecteur). La distance euclidienne entre deux vecteurs est donnée par l'expression:

$d(\mathbf{p},\mathbf{q}) = \sqrt{(p_1-q_1)^{2} + (p_2 - q_2)^{2} + \: ... \: + (p_n - q_n)^{2}}$
<br>
<br> 
<br> 
<img src="Euclidean_distance_2d.png" width="400"/>
<br> 
<br> 

2. Retourner un vecteur contenant toutes les distances (dist). Note, ce vecteur (dist) doit avoir le même nombre de lignes que la matrice $\mathbf{B}$.

3. Retourner l'indice de la ligne de la matrice $\mathbf{B}$ qui est la plus proche de $\mathbf{a}$. Vous pouvez utiliser la fonction argsort de numpy: https://numpy.org/doc/stable/reference/generated/numpy.argsort.html


In [5]:
B = np.array([[1, 2],
              [1.5, 3],
              [3, 4.5],
              [4,5],
              [1, 1.5],
              [2, 3],
              [2, 3.5]])

a = np.array([3.5, 3.5])

In [30]:
distance = np.sqrt(np.sum((B - a) ** 2, axis=1))

In [31]:
np.argsort(distance)

array([2, 6, 3, 5, 1, 0, 4])